### DISCUSSION TITLE
Delete this

### DISCUSSION THREAD

**Discussion by jcheroske** [sct/overseerr#3017] [General]
I just configured Overseerr to be accessible the same way I configure all my services:

http://overseerr.local
http://nas.local/overseerr
http://nas.local:5055

Here is the config. It needs to be tested by others, but I'm hopeful that the documentation at https://docs.overseerr.dev/extending-overseerr/reverse-proxy can be updated to say that it does in fact work behind a base URL.

```
services:
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - "PGID=${PROCESS_GID}"
      - "PUID=${PROCESS_UID}"
      - "TZ=${TIMEZONE}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=web"
      - "traefik.http.routers.overseerr.middlewares=overseerr-stripprefix"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.local`) || PathPrefix(`/overseerr`) || HeadersRegexp(`Referer`, `/overseerr`)"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.http.middlewares.overseerr-stripprefix.stripPrefix.prefixes=/overseerr"
    ports:
      - 5055:5055
    restart: unless-stopped
    volumes:
      - <path_to_overseerr_config>:/config
 ```
