### DISCUSSION TITLE
Can't run Overseerr on Asustor NAS

### DISCUSSION THREAD

**Discussion by anonyme123** [sct/overseerr#3132] [Help]
Hello,

I'm having a hard time setting up Overseerr on an Asustor [NAS](https://www.asustor.com/online/online_help?id=74).
Here is my docker-compose:

```
---
version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
    ports:
      - 5055:5055
    volumes:
      - /share/docker/Overseerr/config:/app/config
    restart: unless-stopped
```
 The container is stuck in a bootloop. The logs say:
```
Error: ENOENT: no such file or directory, open '/opt/yarn-v1.22.19/lib/cli'
            at Obfect.openSync (node: fs: 594:3)
            at Object. readFilesync (node:fs: 462:35)
            at Object.Module._extensions..js (node: internal/modules/cjs/loader: 1143:18)
            at Module. Load (node: internal/modules/cis/loader: 1084:32)
            at Function.Module._ Load (node: internal/modules/cjs/loader: 839:12)
            at Module, require (node: internal/modules/cjs/loader: 1028:19)
            at require (node: internal/modules/cjs/helpers: 102:18)
            at Object .canonymous> (/opt/yarn-v1.22.19/bin/yarn. js:24:13)
            at Module._compile (node:internal/modules/cjs/loader: 1126:14)
            at Object. Module.. extensions.. js (node: internal/modules/cjs/loader: 1180:10) {
      errno: -2,
      syscall: 'open',
      code: 'ENOENT',
      path: 'opt/yarn-v1.22.19/lib/cli'
}
```

Any idea?
