### DISCUSSION TITLE
Interesting interaction with Traefik

### DISCUSSION THREAD

**Discussion by modem7** [sct/overseerr#976] [Help] [answered]
**Describe the bug**
When published via Traefik, if I search anything that has a space, it seems to bug out. It works with anything that doesn't use a space.

**_[Removed video. Please black out sensitive/personal information before posting!]_**

This doesn't occur locally. So I'm pretty sure it's not an overseer issue.

**What version of Overseerr are you running?**
1.19.1

**To Reproduce**
Steps to reproduce the behaviour:

Search for anything with a space. 

**Expected behavior**
For it not to reload constantly. 

**Screenshots**

**Desktop (please complete the following information):**

Docker

**Additional context**
This is less a bug fix request, and more for purposes of future documentation on the Traefik (I suspect?) fix. 

Has anyone seen this behaviour occurring with Traefik?

I've also attempted to remove all middlewares from Traefik's Overseer config, but this is still occurring. 

I've also posted this query here https://community.traefik.io/t/overseer-issue-with-traefik/9766 as it's not really an overseer issue.

**Comment by TheCatLady** [comment, marked as answer]
Hi @modem7!  We have a [sample Traefik configuration in our documentation](https://docs.overseerr.dev/extending-overseerr/reverse-proxy-examples#traefik-v-2), but do not provide support for Traefik itself.  Your best bet is through Traefik's support channels, and I see that you've already reached out there.

That said, you are also welcome to [join our Discord server](https://discord.gg/PkCWJSeCk7) and inquire in #off-topic to see if anyone else is experiencing similar issues.  I am pretty sure we have some users there using Traefik without issue.

**Comment by wickedshrapnel** [comment]
Not seeing this on the latest traefik docker container in my environment. Here is the relevant config. 

```
########start fileConfig.yml #########

http:
 #region routers 
  routers:
    overseerr:
      entryPoints:
        - "https"
      rule: "Host(`overseerr.exampledomain.com`)"
      middlewares:
        - default-headers
      tls: {}      
      service: overseerr  
          

#endregion
#region services
  services:
    overseerr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.100:5055"
        passHostHeader: true   

#endregion
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers

########end fileConfig.yml #########


This static config named fileConfig.yml is referenced in my main traefik.yml file with the following. 

providers:
  providersThrottleDuration: 2
  file:
    filename: /etc/traefik/fileConfig.yml
    watch: true
```
