### ISSUE TITLE
Docker volume warning shows when using Docker named volumes

### ISSUE THREAD

**Issue by andrewvaughan** [sct/overseerr#3885]
### Description

When using a named volume (e.g., this in Docker Compose):

```yaml
    #....
    volumes:
      - "overseerr-config:/app/config"
    
volumes:
  overseer-config:
```

The app still shows the message:

```
The /app/config volume mount was not configured properly. All data will be cleared when the container is stopped or restarted.
```

This is not true, as named volumes are persisted in `/var/lib/docker` and are simply managed by Docker (or Compose).

### Version

1.33.2

### Steps to Reproduce

1. Create a volume with `docker volume create ...`
2. Mount that named volume to Overseerr during Docker setup

### Platform

desktop

### Device

Server

### Operating System

Ubuntu

### Browser

All

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct
