### ISSUE TITLE
Regression: Cannot connect at all to plex

### ISSUE THREAD

**Issue by ChristopherJTrent** [sct/overseerr#4155]
### Description

Attempting to complete the onboarding flow cannot proceed due to "Failed to connect to plex" error.
Plex console shows error message `[Req#12ba6] (Capabilities) Platform 'Overseerr' not matched by plugin platform requirements`

### Version

1.34.0

### Steps to Reproduce

- Install Plex media server and Overseerr inside docker containers
- attempt to complete onboarding
- fail due to "Failed to connect to plex" error
- check plex console
- see the aforementioned error message.

### Logs
None provided as none are present in my `docker logs` output

### Platform

desktop

### Device

Framework Laptop 16

### Operating System

Windows 11

### Browser

Firefox

### Additional Context

Overseerr is running under docker, using the following docker-compose definition. (These settings worked perfectly not three days ago.)
```yml
overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    environment:
        - LOG_LEVEL=debug
        - tz=america/los_angeles
        - PORT=5055
    ports:
        - 5055:5055
    volumes:
        - /plex/config/overseerr:/app/config
```

### Code of Conduct

- [x] I agree to follow Overseerr's Code of Conduct

**Comment by Trisky** [comment]
Hi! 

Seems to work for me. I'll leave my compose.yml file for reference here:

Also a screenshot of the setup wizard screen where I use `plex` as the hostname because thats the name of the container.

```yml
services:
  overseer:
    image: ghcr.io/sct/overseerr:1.34.0
    container_name: overseer
    ports:
      - "5055:5055" 
    environment:
      - TZ=America/New_York 
    volumes:
      - ./overseer/data:/app/data
      - ./overseer/config:/app/config

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    environment:
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex/config:/config
      - ./media:/media
    ports:
      - "32400:32400"

```

<img width="917" height="1029" alt="Image" src="https://github.com/user-attachments/assets/9d8e7b60-8a8e-4983-b83a-d3ddcd338ef3" />
